name: todo_list_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  flutter_adaptive_scaffold: ^0.1.7+2
  uuid: ^4.2.2
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  shimmer_animation: ^2.1.0+1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8

flutter:

  uses-material-design: true
